### PR TITLE
Update plugins.php

### PR DESCRIPTION
**Pull request by Shyzer**
Updated old 404 link on line 164

### CODE REVIEW

**Comment by dgw** [comment]
We are probably better off making the older link work as it used to. Changing this string would require language packs to be updated, as I understand the L10N system.

@LeoColomb How hard would it be to redirect `/awesome` on the new website to the Awesome List?

**Comment by LeoColomb** [comment]
@dgw As hard as understanding why the YOURLS instance in backend is down 😅

**Comment by dgw** [comment]
@LeoColomb Oh no! Well I guess that's why it broke 😂

**Comment by dgw** [comment]
The backend issue has been fixed! 🥳

Thanks @Shyzer for helping us notice the problem.

**Pull request closed without merging**
