### PR TITLE
Prevent YOURLS from displaying encryption warning when password is provided via environment variables

### PR DESCRIPTION
**Pull request by bryanpedini**
Perhaps a fix for #3038.
Maybe, just a quick, dirty solution (first that came in my mind, feel free to propose / do something else).

EDIT: to be clear, I have not tested this yet, I based my PR on top of documentation, code comments and digging around a little. Using Træfik+Docker in production w/ the official image, I have really no easy way to test this out by myself. Perhaps a unit test could do the work for us.

### CODE REVIEW

**Comment by bryanpedini** [comment]
I added a wrapper if to be explicit about the checks during the authentication / encryption phases.
The function could have been easily slipped into the outer if but as said above it would be less clear and there would have been no space for the explanatory comment (if necessary).

Otherwise feel free to just remove the wrapper and merge the two checks toghether :)

**Comment by bryanpedini** [comment]
Damn it, thank you for the CI workflows!! I forgot one closing bracket.

Fixed in last commit.

**Comment by ozh** [comment]
Thanks !

**Comment by ozh** [comment]
About `count($yourls_user_passwords) == 1` : I think it's bound to fail at some point. You could totally have a standard YOURLS setup with multiple user/pwd in the config, yet also use another auth mechanism using env vars.

Isn't "username and password are provided by environment" the only red flag we need to care about ?

**Comment by bryanpedini** [comment]
> Isn't "username and password are provided by environment" the only red flag we need to care about ?

Sure... should I just remove it then?

**Comment by ozh** [comment]
I'm refactoring things from your PR, and adding some unit tests, no worries

**Comment by bryanpedini** [comment]
Sure, you have edit access, feel free to edit my branch before merging the PR :)
Thank you for the consideration.

**Comment by ozh** [comment]
Thanks @bryanpedini :) I hope this will fix the original issue :-P (it should)

**Comment by bryanpedini** [comment]
Thank you for giving me the opportunity to contribute! (it's not obvious, let me tell you...)

**Pull request merged**
