### PR TITLE
Fix logout in stats page

### PR DESCRIPTION
**Pull request by eli0tc**
I noticed that I couldn't logout when I was on the stats page.
I changed the relative path to a full path using yourls_admin_url() and now it works.

### CODE REVIEW

**Comment by LeoColomb** [comment]
This looks great! :sparkles:
Thanks for your contribution @eli0tc!

What is your motivation for this change?

**Comment by eli0tc** [comment]
The link rendered looked like "https://domain.name/installation_path/uuuu+?action=logout'' which had no effect.

**Comment by ozh** [comment]
I think this is specific to nginx, I can totally logout while on a stat page.

This causes a change of behaviour (as of now you stay on the stats page and are presented the login form ; your patch redirects you from the stats page to the admin area) but I don't think that's a big deal. I'm merging this, thanks for your PR.

It's just annoying that nginx seems to handle cookies in such a peculiar way (there's an ongoing issue with login on nginx). Out of curiosity, on a URL like `/bleh+?action=omg`, what does `$_REQUEST` look like on your setup? I don't get why [this](https://github.com/YOURLS/YOURLS/blob/master/includes/functions-auth.php#L16-L21) would fail...

**Comment by eli0tc** [comment]
$_REQUEST is empty.
It seems that no get parameters are passed.

**Pull request merged**
