### PR TITLE
Updated default links from 'http' to 'https'

### PR DESCRIPTION
**Pull request by jaas666**

### CODE REVIEW

**Review by LeoColomb — CHANGES_REQUESTED** [review]
Looks like to be a great start, thanks @jaas666!
One thing left is the unit tests spec, where the URL must also reflect the changes.
See failing tests on the PR.

**Comment by jaas666** [comment]
Ahhhh.. didn't knew about that. Took me a while but I found out what you are talking about.

Submitted the change.. altough I don't know if done correctly.

**Review by LeoColomb — APPROVED** [review]
Yes, correctly done.

**Comment by jaas666** [comment]
Great.. so officially my first contribution approved.. Yayy.
Thanks.

**Pull request merged**
