### PR TITLE
Wrapped `$user` in `preg_quote` function

### LINKED ISSUE #3364: Auto encrypting password does not work if username contains a square bracket
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.1

### Description

If a user's name includes square brackets, the password will not be encrypted and a preg_replace error is reported.

### Expectation

The password to be encrypted without any issue.

### Reproduction steps

Add

```php
$yourls_user_passwords = array(
    'testuser[2]' => 'password',
);
```

### Context

Seems like the bracket might be breaking something for the `preg_replace` pattern.

https://github.com/YOURLS/YOURLS/blob/3b69f2be52fdfa08c54eccdcb7b3cfc55560a851/includes/functions-auth.php#L216

I only tried curly braces as an additional test, which did work, but even just 1 square bracket breaks the encryption.

### PR DESCRIPTION
**Pull request by SXN31**
This pull request is to fix #3364 where a username with square brackets will prevent encryption of the password. Thanks to ozh for showing me the way!

### CODE REVIEW

**Review by LeoColomb — CHANGES_REQUESTED** [review]
Thanks!
Just a styling improvement 🔍

**Comment by ozh** [comment]
Nice and fast, thanks :)

What would be really cool would be to update unit tests as well, in [tests/data/auth/config-test-auth.php](https://github.com/YOURLS/YOURLS/blob/master/tests/data/auth/config-test-auth.php), so we make sure that in the future this edge case is still correctly dealt with

**Comment by SXN31** [comment]
> 

Just so I'm understanding the test enough, is it sufficient to add another line with a user with brackets and a random password into the array?

**Comment by ozh** [comment]
I'm quite lagging behind several PR's, sorry for that. Will look into this asap

**Pull request merged**
