### PR TITLE
Unobtrusive message for people peeping in their console

### PR DESCRIPTION
**Pull request by ozh**
Thoughts ?

### CODE REVIEW

**Comment by dgw** [comment]
"toggable" message?

**Comment by joshp23** [comment]
this might be interesting if the message could be filtered

**Comment by ozh** [comment]
Yeah, toggable with filter `shunt_js_easter_egg`

Regarding filtering the message itself: well if someone wants to display their own, it has always been possible using action `html_head`. It's not really a new "feature" per se

**Comment by ozh** [comment]
So, I understand this isn't popular. Ok :)

**Pull request closed without merging**
