### PR TITLE
#1898 - Plugin validation I

### PR DESCRIPTION
**Pull request by peterberbec**
https://github.com/YOURLS/YOURLS/issues/1898

let's verify the file at least starts with <?php

### CODE REVIEW

**Comment by ozh** [comment]
Sane idea, but very confusing code IMHO:
```
	if ( ... ) {
		if ( ... )
		return false;
	}
	else return false;
	return true;
```

**Comment by peterberbec** [comment]
is it the lack of comments, or the nested ifs? let me think on it for a while, I might be able to get another way.

**Comment by peterberbec** [comment]
This reads much better.

If this gets in, are the tests of the filename still needed? We have already opened the file and proved it starts with `"<?php"`. Could
`		false !== strpos( $file, '..' )		// check filename for sanity I
		OR
		false !== strpos( $file, './' )		// check filename for sanity I
		OR`
be removed?

**Comment by ozh** [comment]
Back on this PR after so long

I'm dropping the idea because depending on how the PHP plugin file is saved (UTF8 with BOM or without BOM), the first 5 **or 8** bytes are needed to fetch the opening `<?php`. (For most folks, fetching first 5 bytes [is OK](https://3v4l.org/RISfr) and the file begins with `<?php` at position 0, but for some folks we'd need 8 bytes and the file would begin with `<?php` at position **3**.)

So, I don't think this is worth the hassle and potential troubles. I'm all ears if someone has a *simple* way of checking this ("simple", as in "will work in 100% cases"), otherwise let's just assume that folks creating a file named `plugin.php` and not starting it with `<?php` just deserve what they'll get :)

**Pull request closed without merging**
