### PR TITLE
Fix Markdownlint

### PR DESCRIPTION
**Pull request by Saibamen**

### CODE REVIEW

**Comment by LeoColomb** [comment]
Not really sure to get the benefits here.
Has this PR been made with Hacktoberfest in mind?

**Comment by Saibamen** [comment]
>Not really sure to get the benefits here.

Standarization of your Markdown files. Just like ESLint for JavaScript.

>Has this PR been made with Hacktoberfest in mind?

Yes

**Comment by LeoColomb** [comment]
Then I'm not sure whether I'm willing to merge this change, this is not an expected PR for Hacktoberfest IMO.
@YOURLS/core What do you think about this? Do we care?

**Comment by dgw** [comment]
> @YOURLS/core What do you think about this? Do we care?

Hacktoberfest doesn't require code contributions, certainly. Everything in this PR (except adding "sponsor" or "backer" to the images, that seems unnecessary) is something I'd do myself in a documentation cleanup pass: removing HTML where it's not needed, correcting whitespace, etc. The difference is that I almost always do those manually (and thus probably miss things).

My only objection would be that this doesn't add any checks/tools to the project so the Markdown will be linted automatically, but that would require discussion. (Is it a scheduled task, or does it run against PRs? Does it apply fixes automatically or add a Failed annotation that requires manual action? etc.)

**Comment by ozh** [comment]
You already know how I feel about linters ;-)

**Comment by LeoColomb** [comment]
> Hacktoberfest doesn't require code contributions, certainly.

Yeah yeah, I do know that. But Hactoberfest is here to promote valuable contributions, with or without code.
Here I'm not convinced of the value, basically remove one or two whitespace, and not to mention linting markdown is very opinionated.
My main concern is this PR being [very very close to the limit of the rules](https://hacktoberfest.com/participation/#spam):

> Hacktoberfest is about contributing meaningfully to open-source projects. Here are some examples of low-quality pull/merge requests that won’t count towards Hacktoberfest.
> * Automated pull/merge requests: scripted opening pull requests to remove whitespace, fix typos or optimize images.

I mean:
* https://github.com/Leaflet/Leaflet/pull/8599
* https://github.com/IonicaBizau/wp-floating-social/pull/18

**Comment by dgw** [comment]
> I mean:
> 
> * [Fix Markdownlint Leaflet/Leaflet#8599](https://github.com/Leaflet/Leaflet/pull/8599)
> * [Fix Markdownlint IonicaBizau/wp-floating-social#18](https://github.com/IonicaBizau/wp-floating-social/pull/18)

Oh… Yeah, that's a pattern.

**Pull request closed without merging**
