### PR TITLE
Issue 2307 database creation fixes

### PR DESCRIPTION
**Pull request by Seegras**
Two fixes for https://github.com/YOURLS/YOURLS/issues/2307
- patch by teyeheimans to report db-creation errors
- patch by me to lower key size to 191, to accommodate mysql 5.6 databases using utf8mb4

### CODE REVIEW

**Comment by ozh** [comment]
Thanks!
Can you elaborate on the 191 chars bit, to "accomodate utf8mb4 on mysql 5.6" ? What is it exactly?

**Comment by ozh** [comment]
OK, read a bit about utf8mb4 and this (weird?) 191 char limit. Thanks a lot.

The PR needs a slight reworking: in order to trigger the DB upgrade, you need to bump the [DB version](https://github.com/YOURLS/YOURLS/blob/master/includes/version.php#L12) (arbitrary number, `483` will be fine), to [trigger a redirection](https://github.com/YOURLS/YOURLS/blob/master/includes/Config/Init.php#L92-L95) to the upgrade page. A newer function in `functions-upgrade.php` must reflect the newer DB version: don't change function yourls_upgrade_482(), create a newer one that will be run (`yourls_upgrade_483()` for instance)

Tell me if that's clear or if I can help

**Comment by Seegras** [comment]
Oh, IC. But I'm sorry, I'm no longer interested. Now that it worked, it turned out you can only have one redirect per URL, which is a showstopper for me, so I looked at a different software.

**Comment by dgw** [comment]
@Seegras You can, though. It's just a config change away. See #1901.

**Comment by ozh** [comment]
Some of this PR is included in #2690

**Pull request closed without merging**
