### PR TITLE
Fixed redirect failure after login

### PR DESCRIPTION
**Pull request by hangxingliu**
This bug appears on the website isn't hosted on port 80/443.
Use `HTTP_HOST` to replace the `SERVER_NAME`.

For example, The `$_SERVER['SERVER_NAME']` maybe `127.0.0.1` when the website is hosted on `127.0.0.1:8008`. But `$_SERVER['HTTP_HOST']` will be `127.0.0.1:8008` in this situation.

### CODE REVIEW

**Comment by dgw** [comment]
Don't revert #2542.

This looks like it will _always_ add `:port` to the URL if `$_SERVER['HTTP_HOST']` is not set and the code has to fall back on `$_SERVER['SERVER_NAME']`. We really don't want or need it for vanilla `http://` on port 80 and `https://` on 443. It's more likely to confuse users than not.

**Comment by hangxingliu** [comment]
> Don't revert #2542, please.

Sorry, I forgot to pull the upstream code before modify.

And I modify the code around generating redirect URL. It would not add `:80` and `:443` anymore.

**Comment by ozh** [comment]
Back (after so long, sorry) at this : I'm not sure why we're not simply using YOURLS_SITE instead of this complex $_SERVER['SERVER_NAME'] juggling.

If anyone here still alive : https://github.com/YOURLS/YOURLS/issues/2603#issuecomment-589594461

**Comment by ozh** [comment]
Trying to make things even simpler. I'm closing this PR and looking forward to fixing things with PR #2625, please report there

**Pull request closed without merging**
