### PR TITLE
RFC 2606 / RFC 6761 compliance.

### PR DESCRIPTION
**Pull request by danielhoherd**
Changing this to be RFC 2606 / RFC 6761 compliant.  http://www.iana.org/domains/reserved

I noticed this while testing when my browser was redirected from site.com to salesforce.com.

### CODE REVIEW

**Comment by LeoColomb** [comment]
:+1:

**Comment by ozh** [comment]
I would prefer it to be define( 'YOURLS_SITE', 'http://your-own-domain' ); with the comment right before explaining that http://your-own-domain should be replaced with the domain -- or subdomain -- and path if applicable where the user has installed YOURLS.

The key point here being that the domain placeholder should not resolve to something actual (eg 'site.com' was, in retrospect, a bad idea that is confusing average Joe, and example.com is not better. See multiple issues about salesforce.

**Comment by LeoColomb** [comment]
Should help to avoid #1719 & #1870.

**Comment by ozh** [comment]
Plan:
- replace `site.com` in phpdoc comments with `example.com`, as suggested here, because it's cleaner and makes sense for devs who read the comments
- replace http://yoursite.com with http://your-own-domain-here.com/ in readme.html, user/config-sample.php and sample-public-front-page.txt to make things very self explanatory

@danielhoherd fancy updating your PR?

**Comment by LeoColomb** [comment]
@ozh http://your-own-domain-here.com/ <- :laughing:

**Comment by LeoColomb** [comment]
But why not `example.com` even in the config?

**Comment by ozh** [comment]
Because Joe Newbie doesn't get why his install gets redirected to site.com (then salesforce.com or whatever), and will not understand more with example.com.

**Comment by chtaube** [comment]
Additional idea: Do a one-time check (probably in install.php) by comparing `YOURLS_SITE` against the default value shipped in the config file. Give a friendly message to the user if he didn't change `YOURLS_SITE`.

**Comment by ozh** [comment]
@chtaube Interesting idea. In the long run though that would mean two files to maintain with mostly the same content (ie default value for some var in `config-sample.php` and that same thing in `install.php/yourls_default_checks()` or whatever).

**Pull request closed without merging**
