### PR TITLE
Make password auto encryption work when password contains slash(es)

### LINKED ISSUE #1987: Auto encrypting passwords doesn't work if password contains forward slashes
If the password contains one or more forward slashes, auto encryption doesn't work and raises a `'preg_replace problem'`.

The culprit is the prog_quote call in line 173 of includes/functions-auth.php. Should be `preg_quote( $password, '/' )` instead of `preg_quote( $password, '-' )`

Thanks,

Bernie

### PR DESCRIPTION
**Pull request by berndblume**
Fix #1987

### CODE REVIEW

**Comment by berndblume** [comment]
Travis-CI doesn't run through because composer is outdated.

**Comment by LeoColomb** [comment]
Looks good! Thanks :smile:

**Comment by ozh** [comment]
If I'm correct, this doesn't work with a password like `'lol .\+*?[^]$(){}=!<>|:-/' . "'" . '"'` (ie containing all preg special chars)

**Comment by berndblume** [comment]
It should work with that password because prog_quote does quote ALL special prog chars: [link to php docs] (http://php.net/manual/en/function.preg-quote.php). I haven't tested that particular password ;-), but it should work.

The thing is: for some reason, the second argument ($delimiter) to prog_qoute was passed as '-', while in reality we're using the standard '/' as the delimiter. After my change, passing '/' as the delimiter rather than '-', it works with passwords that contain slashes as well as with passwords that contain dashes. For all the other special prog characters, prog_quotes them automatically independent of the $delimiter argument.

In essence: everything should be fine by now.

**Comment by ozh** [comment]
My comment was based on actual tests with the unit test suite. It doesn't work. Not sure why, didn't dig deep enough, but it doesn't work.

**Comment by ozh** [comment]
I stand corrected -- my test was flawed, your PR indeed fixes the forward slash problem. Much thanks!

**Pull request merged**
