### PR TITLE
New plugin hook for manipulating the HTTP referrer

### PR DESCRIPTION
**Pull request by mibe**
This allows plugins to change the HTTP referrer.

The code adds a new function, ```yourls_get_referrer``` which is called by ```yourls_log_redirect```. A new hook is added, ```get_referrer```, so that plugins can change the referrer information.

### CODE REVIEW

**Comment by ozh** [comment]
Sure, why not. This said, the filter should always be the last thing before return so plugins can always manipulate the value. Here, with no referrer set, a plugin cannot catch the `'direct'` return value. The logic needs to be changed to 
- do checks
- assign value
- only one return in the function, filtered

**Comment by mibe** [comment]
Alright, I've changed the code so that the plugin is also called when no referrer was provided.

BTW: I used ```yourls_get_user_agent``` as a template. If there is no user agent set, it will return without calling the plugin. Is this a bug then?

**Comment by ozh** [comment]
Not a "bug" but definitely something I could have been more careful about :) Fancy fixing that yourls_get_user_agent() as well while you're at it?

**Comment by ozh** [comment]
Thanks!

**Pull request merged**
