### PR TITLE
Fix is_private overruling

### LINKED ISSUE #2858: Overruling is_private not possible anymore
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
Overruling `yourls_is_private()` is not possible anymore

**To Reproduce**
1. Set `define( 'YOURLS_PRIVATE', true )` and `define( 'YOURLS_PRIVATE_INFOS', false )`
2. Open info page of a short url
3. See that it's still private

**Expected behavior**
`YOURLS_PRIVATE_INFOS` and `YOURLS_PRIVATE_API` should have any effect.

**Actual behavior**
They don't have any effect.

**Versions**
`1.8`

**Additional context**
The problem is in here:
https://github.com/YOURLS/YOURLS/blob/510851c91866063f3e3bc1ac40c8c4c2caf16293/includes/functions.php#L496-L517
`$private` will always be true.

I will provide a pull request.

### PR DESCRIPTION
**Pull request by Virinum**
Fixes #2858

### CODE REVIEW

**Review by dgw — APPROVED** [review]
Assuming I haven't fallen victim to late night code review syndrome and missed something, LGTM

**Comment by ozh** [comment]
While we're at it, this function looks a bit dumb to me. Wouldn't it be simpler with the following, less nested `if`, less cyclomatic complexity and more readability :

```php
function yourls_is_private() {
    // Either the value as defined in config.php, or false if undefined
    $private = defined( 'YOURLS_PRIVATE' ) && YOURLS_PRIVATE;

    // Allow overruling for particular pages:
    if ( yourls_is_API() && defined( 'YOURLS_PRIVATE_API' ) ) {
            $private = YOURLS_PRIVATE_API;
    }
    elseif ( yourls_is_infos() && defined( 'YOURLS_PRIVATE_INFOS' ) ) {
            $private = YOURLS_PRIVATE_INFOS;
    }

    return yourls_apply_filter( 'is_private', $private );
}
```

Or am I missing something ?

**Comment by Virinum** [comment]
With this `YOURLS_PRIVATE_API` and `YOURLS_PRIVATE_INFOS` can always overrule `YOURLS_PRIVATE`. Is this wanted?

Because the code before made overruling only possible if `YOURLS_PRIVATE` was set to true.

**Comment by ozh** [comment]
Indeed, you're right. Let's stick to this original intention, for compat purpose. People willing to do otherwise (for instance having a _public_ install yet restrict access to the API) can still use the filter

So,

```php
function yourls_is_private() {
    $private = false;

    if ( defined( 'YOURLS_PRIVATE' ) && YOURLS_PRIVATE ) {

        $private = true;

        // Allow overruling for particular pages:

        // API
        if ( yourls_is_API() && defined( 'YOURLS_PRIVATE_API' ) ) {
            $private = YOURLS_PRIVATE_API;
        }
        // Stat pages
        elseif ( yourls_is_infos() && defined( 'YOURLS_PRIVATE_INFOS' ) ) {
            $private = YOURLS_PRIVATE_INFOS;
        }
        // Others future cases ?
    }

    return yourls_apply_filter( 'is_private', $private );
}
```

?

**Comment by Virinum** [comment]
We can remove one more line, I think:

```php
function yourls_is_private() {
    $private = defined( 'YOURLS_PRIVATE' ) && YOURLS_PRIVATE;

    if ( $private ) {

        // Allow overruling for particular pages:

        // API
        if ( yourls_is_API() && defined( 'YOURLS_PRIVATE_API' ) ) {
            $private = YOURLS_PRIVATE_API;
        }
        // Stat pages
        elseif ( yourls_is_infos() && defined( 'YOURLS_PRIVATE_INFOS' ) ) {
            $private = YOURLS_PRIVATE_INFOS;
        }
        // Others future cases ?
    }

    return yourls_apply_filter( 'is_private', $private );
}
```

What do you think?

**Comment by ozh** [comment]
@Virinum looks great, could you update the PR ?

**Comment by Virinum** [comment]
PR updated

**Pull request merged**
