### PR TITLE
Update placeholder to https://

### PR DESCRIPTION
**Pull request by flokX**
and motivate users to use the secure version of the url.

### CODE REVIEW

**Comment by ozh** [comment]
This is the input box where people enter the URL to shorten.

**Comment by dgw** [comment]
@ozh Yes, and I actually think it's a reasonable place to show `https://` as a subtle way to maybe get users to check if their link is available over HTTPS if it isn't already the secured version.

**Comment by LeoColomb** [comment]
I second you @dgw. I think also it's worth adding it.

**Comment by ozh** [comment]
The people have spoken!

**Pull request merged**
