### PR TITLE
Design & Style

### LINKED ISSUE #1234: Future feature: theming API
> (originally submitted on 2012-11-11T11:54:07.000Z at Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github))

In the future it would be cool if there was support for theming YOURLS pages (admin pages &amp; stat pages)

Principles :

- There will be a /user/themes directory, and a theme would consist in a subdirectory such as /user/themes/my_theme containing at least a theme.css, an optional components: images, js files, and a theme.php file if the theme also implements PHP stuff (just like a plugin does)

- theme.css files will begin with the same kind of header as in plugin files

- There will be an /admin/theme.php management page, much like the current plugins.php page (see what can be shared)

Requirements:

- better HTML &amp; CSS code in all pages. Right now there are too many hardcoded stuff, too much HTML &amp; PHP soup, and too many inconsistencies in CSS (sometimes using classes instead of IDs or the other way round). The goal here is to have something clean enough that with changing just a CSS, everything can be properly styled and customized

- Functions to enqueue &amp; dequeue CSS &amp; JS files that are injected in the &lt;head>

### PR DESCRIPTION
**Pull request by LeoColomb**
Redefinition of the interface to improve YOURLS experience.

yourls
_Second interface preview. Need completions._
## Interface Styling
- [x] Design with HTML5 - CSS3 
  - [Bootstrap 3.0.0](https://github.com/twitter/bootstrap/pull/6342)
  - [Flat UI](http://designmodo.github.io/Flat-UI/)
  - [Font Awesome](http://fontawesome.io/)
  - Introduce Responsive-design
- [x] Clean HTML template
  - Clean declarations
  - More separated container
    - Header simplifying
    - Nav improving
    - Foot cleaning
- [x] Basic Installation corrections
  - Be friendly with errors - notices
  - Fix interface when re-loading installation
- [x] Loading pages & animation
- [x] Reduce request and loading time
  - Minimize in one file all code
- [x] Improve JavaScript
  - jQuery [2.0.0](http://blog.jquery.com/2013/04/18/jquery-2-0-released/)
  - ZeroClipboard
  - New interactions
- [x] Move assets in `assets/` folder
- [x] Move flags into CSS
## Themes
- [x] Create `theme-sample` repo
  - Import & use LESS files
- [x] Allow overwriting official style - resolves #1234
  - CSS - JS enqueue
  - Filters
- [x] Customize HTML structure
- [x] Add [full bootstrap](https://github.com/LeoColomb/full-bootstrap-yourls) theme
### Coding Style
- [x] Clean PHP with HTML
- [x] Apply strictly standards everywhere
### Specific Cases
- [x] Fix unlicensed favicon
- [x] Remake graphically `readme.html` - resolves #1390
- [x] Twitter profile

### CODE REVIEW

**Comment by mtsmayad** [comment]
Hello, what happened to the newly designed interface ... how to get it ????

**Comment by LeoColomb** [comment]
@mtsmayad The redesign is still work-in-progress. 🙂

**Comment by JayHoltslander** [comment]
I whipped up this mockup yesterday of what I'd personally like to see for an updated YOURLS interface. (Material design)
Thought I'd post it in here for posterity. https://codepen.io/j_holtslander/pen/oNjGaYw

**Comment by soneji** [comment]
Hi @LeoColomb is there an ETA for 2.0?

Thanks

**Comment by ozh** [comment]
@soneji not at all

**Comment by LeoColomb** [comment]
@LeoColomb Soon 😉

**Comment by soneji** [comment]
image

**Comment by JasonHK** [comment]
> image
> 

@soneji Please don't post any unnecessary contents here, thanks.

**Comment by soneji** [comment]
Where is the `2.0-wip` branch? I cannot find it - can I look at the changes?

**Pull request closed without merging**
